### ISSUE TITLE
希望上传下对应的官方版本吧

### ISSUE THREAD

**Issue by cddehsy** [h3110w0r1d-y/termius-cracked#1]
希望上传下对应的官方版本吧

**Comment by h3110w0r1d-y** [comment]
最新版本的修改方法没有变化，直接在官网下载安装包，然后按照README中写的修改那个文件即可

**Comment by iClouds** [comment]
您好 有没有汉化及禁止更新的方法呢 非常感谢分享

**Comment by h3110w0r1d-y** [comment]
禁止更新：看下最新的Readme，删除目录下的app-update.yml即可阻止更新
汉化：网上有相关汉化方法，写个脚本批量替换

**Comment by dkzsys** [comment]
您好，希望能学习了解一下破解app.asar的原理以及方法，不知是否能分享？谢谢！

**Comment by h3110w0r1d-y** [comment]
@dkzsys 我是这样做的，先通过抓包找到这个软件获取用户信息的请求，然后在解包后的文件中全局搜索那个请求的路径，就像下面这个截图
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/52311174/211136828-ab965947-21af-4aa3-9f48-09f7ccce879c.png">
然后找这个`Kn`常量在哪个地方使用过，很容易就可以找到了，这个函数就是用来获取用户信息的
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/52311174/211137701-9b3efd69-f41f-4544-b1ef-002be04554bf.png">
然后继续找在哪调用了这个函数，一共就找到三四个地方
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/52311174/211138330-3bb48204-7b17-4882-badc-3d408b75bc39.png">
找到这里后剩下的就好办了，这个函数的返回值就是用户信息，写几行代码把一些判断是不是付费用户的字段改成True即可。

为了得到真实的订阅用户的返回数据我还特意付了一个月会员
<img width="53" alt="image" src="https://user-images.githubusercontent.com/52311174/211138911-1adef0be-cf52-4fb1-b475-c2cb36027594.png">

**Comment by dkzsys** [comment]
@h3110w0r1d-y 非常感谢，学习了！刚试了修改background-process.js。我的账号目前还在试用期，UI还是显示的Trial，估计过期之后会更新吧（？）。
另外，请教一下，破解后，本地的autocompletion功能是否能正常工作？Sync vault（多设备同步）应该不工作了吧？

**Comment by Code317** [comment]
大佬牛啤！学习了！
