### ISSUE TITLE
希望上传下原版安装包

### ISSUE THREAD

**Issue by cddehsy** [h3110w0r1d-y/termius-cracked#5]
希望上传下原版安装包，不然根本用不了

**Comment by h3110w0r1d-y** [comment]
安装包去官网下就可以

**Comment by anoxtoxic** [comment]
isn't worked in termius 7.59.2 please check new
plan stay on trial or expired

**Comment by anoxtoxic** [comment]
@h3110w0r1d-y 在 termius 7.59.2 中不起作用
sorry i use translate i can't speak chinese

**Comment by h3110w0r1d-y** [comment]
Fixed

**Comment by cddehsy** [comment]
官网的只有最新的，每次都对不上版本

**Comment by h3110w0r1d-y** [comment]
刚刚已经更新了README，最新版本的返回参数中增加了access_objects，按照README中的说明修改就可以，不用非得对上版本号

**Comment by zhangbei1988** [comment]
能否提供下修改的js部分截图，根据最新的readme还是无法成功

**Comment by huyanhai** [comment]
不能保存配置

**Comment by NoChizPlz** [comment]
should it be pack after editing?

**Comment by h3110w0r1d-y** [comment]
> should it be pack after editing?

don't repack
