### ISSUE TITLE
tips：修改js前要把对应的方法的注释取消

### ISSUE THREAD

**Issue by langzikUn521** [h3110w0r1d-y/termius-cracked#6]

**Comment by NintendoLink** [comment]
没看懂，折腾了半天也不知道第二步怎么替换。能详细说下么，大佬

**Comment by langzikUn521** [comment]
【修改app/js/background-process.js】执行这个步骤的时候，你会发现搜索定位到【await this.api.bulkAccount】这段代码的时候，相关代码是被注释掉的，也就是，你得把前面注释符号删除，不然你修改的代码不起作用

**Comment by langzikUn521** [comment]
> 没看懂，折腾了半天也不知道第二步怎么替换。能详细说下么，大佬

【修改app/js/background-process.js】执行这个步骤的时候，你会发现搜索定位到【await this.api.bulkAccount】这段代码的时候，相关代码是被注释掉的，也就是，你得把前面注释符号删除，不然你修改的代码不起作用

**Comment by langzikUn521** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/59392864/388e9ada-2bde-4207-a7df-5652b6105652)
你可以参考相应的行数来对比下

**Comment by NintendoLink** [comment]
我找了半天，也没找到怎么样解除注释的，大佬能发我下这个文件么，求求谢谢了.

**Comment by langzikUn521** [comment]
> 

你把你的发上来，我帮你调整好发出来，顺带问一下你的版本号是多少

**Comment by NintendoLink** [comment]
谢谢大佬，我模仿你的文件，改了下，return .......这边需要怎么改呢？
![Uploading image.png…]()

**Comment by NintendoLink** [comment]
谢谢大佬解答。
我模仿你的配置文件，想问下return ......这边怎么修改 ？
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/13000875/4fc24439-3a76-455b-b9d5-b807089e5b59)

**Comment by NintendoLink** [comment]
字符太多，方便加一下大佬的联系方式么？18705192873

**Comment by langzikUn521** [comment]
> turn ......这边怎么修改

return不需要改的，原来的代码里面就已经包含了return的内容，只是被注释掉而已，你去掉注释你就看见了，最简单的方法，你发我一份你的js，没修改过的，我这边帮你调整好，你对比下就知道了

> 谢谢大佬解答。 我模仿你的配置文件，想问下return ......这边怎么修改 ？ ![image](https://user-images.githubusercontent.com/13000875/251702047-4fc24439-3a76-455b-b9d5-b807089e5b59.png)

**Comment by langzikUn521** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/59392864/14207bf0-5113-41b6-a85d-a02e50269d16)
你看原始文件的第123行，这里的var....是被注释掉的，意味着这段代码不生效，最简单的方法在var前面直接回车新增一行

**Comment by langzikUn521** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/59392864/9b7c8185-e435-49b1-9228-0ff6005e2234)
此时，你再根据作者的方法，定位到【await this.api.bulkAccount】，把【const e=await this.api.bulkAccount();】里面的const改成var，改完以后就变成【var e=await this.api.bulkAccount();】，原始代码在【const e=await this.api.bulkAccount();】后面是接了return....，这个也不用做任何修改

**Comment by langzikUn521** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/59392864/1dd142b1-ec72-4c7c-b262-68bfe0b01f15)
接着你在return前面插入作者readme里相应的代码就行了，我这为了方便给你看，我换行显示了

**Comment by langzikUn521** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/59392864/3ce91356-603f-4ea1-9777-33a4f20486bf)

**Comment by langzikUn521** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/59392864/b9a216e2-591b-4853-88aa-a4bc31437f94)
这下应该能懂了吧

**Comment by NintendoLink** [comment]
谢谢大佬耐心指导.
折腾到现在还是启动出问题,不打算折腾了，在mac terminal就手动ssh/scp好了.
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/13000875/aff5bee8-4422-4381-8b14-6a71c95fb7e9)
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/13000875/d9cb7d7a-030c-42f7-84f1-d0b6f1cdec0d)
<img width="740" alt="image" src="https://github.com/h3110w0r1d-y/termius-cracked/assets/13000875/de30eb62-76cc-4a88-9ba1-aa283a900100">
再次感谢terminus开发者，感谢大佬！

**Comment by h3110w0r1d-y** [comment]
> ![image](https://user-images.githubusercontent.com/59392864/251704080-14207bf0-5113-41b6-a85d-a02e50269d16.png) 你看原始文件的第123行，这里的var....是被注释掉的，意味着这段代码不生效，最简单的方法在var前面直接回车新增一行

这里没有被注释，`*/`是注释结束，编辑器有问题，语法高亮没有渲染出来而已

**Comment by NintendoLink** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/13000875/19620e11-21bc-4e65-80a6-d7ce818564e2)
问题找到了，是在执行完`asar extract app.asar ./app`这一行命令之后，termius就显示文件错误

**Comment by h3110w0r1d-y** [comment]
> ![image](https://user-images.githubusercontent.com/13000875/252203286-19620e11-21bc-4e65-80a6-d7ce818564e2.png) 问题找到了，是在执行完`asar extract app.asar ./app`这一行命令之后，termius就显示文件错误

这是正常的，执行一下`sudo xattr -r -d com.apple.quarantine /Applications/Termius.app`

**Comment by NintendoLink** [comment]
感谢大佬.
1、修改完所有配置之后，执行`sudo xattr -r -d com.apple.quarantine /Applications/Termius.app`,还是显示文件损坏
2、打开一次app之后，执行`sudo xattr -r -d com.apple.quarantine /Applications/Termius.app`，显示Operation not permitted
mac os:13.4
termius:7.59.2

**Comment by superjinge** [comment]
async updateUserProfile() {
            var e=await this.api.bulkAccount();
            e.account.pro_mode=true;
            e.account.need_to_update_subscription=false;
            e.account.current_period={
                "from": "2022-01-01T00:00:00",
                "until": "2099-01-01T00:00:00"
            };
            e.account.plan_type="Premium";
            e.account.user_type="Premium";
            e.student=null;
            e.trial=null;
            e.account.authorized_features.show_trial_section=false;
            e.account.authorized_features.show_subscription_section=true;
            e.account.authorized_features.show_github_account_section=false;
            e.account.expired_screen_type=null;
            e.personal_subscription={
                "now": new Date().toISOString().slice(0, -5),
                "status": "SUCCESS",
                "platform": "stripe",
                "current_period": {
                    "from": "2022-01-01T00:00:00",
                    "until": "2099-01-01T00:00:00"
                },
                "revokable": true,
                "refunded": false,
                "cancelable": true,
                "reactivatable": false,
                "currency": "usd",
                "created_at": "2022-01-01T00:00:00",
                "updated_at": new Date().toISOString().slice(0, -5),
                "valid_until": "2099-01-01T00:00:00",
                "auto_renew": true,
                "price": 12.0,
                "verbose_plan_name": "Termius Pro Monthly",
                "plan_type": "SINGLE",
                "is_expired": false
            };
            e.access_objects=[{
                "period": {
                    "start": "2022-01-01T00:00:00",
                    "end": "2099-01-01T00:00:00"
                },
                "title": "Pro"
            }]
             return ......
             const e = await this.api.bulkAccount();
            return await this.setUserProfile(e), e
        }  试试这样

**Comment by superjinge** [comment]
![image](https://github.com/h3110w0r1d-y/termius-cracked/assets/31129726/fd024090-3e10-4ecc-8d81-f68d756b448d)
